const PASSWORD = 'HSB2026';
let state = { tab:'inicio', q:'', muscle:'todos', type:'todos', current:null };

const muscles = ['Pecho','Espalda','Hombro','Bíceps','Tríceps','Cuádriceps','Isquios','Glúteo','Gemelos','Abdomen'];
const types = ['Peso libre','Poleas','Máquinas'];

const baseExercises = [
 ['Press banca con barra','Pecho','Peso libre','Barra + banco','Pecho','Tríceps, hombro anterior','https://www.youtube.com/watch?v=rT7DgCr-3pg'],
 ['Press inclinado con mancuernas','Pecho','Peso libre','Banco inclinado + mancuernas','Pecho superior','Tríceps, hombro anterior','https://www.youtube.com/watch?v=8iPEnn-ltC8'],
 ['Aperturas con mancuernas','Pecho','Peso libre','Banco + mancuernas','Pecho','Hombro anterior','https://www.youtube.com/watch?v=eozdVDA78K0'],
 ['Fondos en paralelas pecho','Pecho','Peso libre','Paralelas','Pecho inferior','Tríceps','https://www.youtube.com/watch?v=2z8JmcrW-As'],
 ['Press en polea de pie','Pecho','Poleas','Doble polea','Pecho','Tríceps','https://www.youtube.com/watch?v=taI4XduLpTk'],
 ['Cruce de poleas alto','Pecho','Poleas','Doble polea','Pecho','Hombro anterior','https://www.youtube.com/watch?v=taI4XduLpTk'],
 ['Cruce de poleas bajo','Pecho','Poleas','Doble polea','Pecho superior','Hombro anterior','https://www.youtube.com/watch?v=taI4XduLpTk'],
 ['Press pecho en máquina','Pecho','Máquinas','Máquina press','Pecho','Tríceps','https://www.youtube.com/watch?v=sqNwDkUU_Ps'],
 ['Press convergente','Pecho','Máquinas','Máquina convergente','Pecho','Tríceps','https://www.youtube.com/watch?v=sqNwDkUU_Ps'],
 ['Pec deck','Pecho','Máquinas','Máquina aperturas','Pecho','Hombro anterior','https://www.youtube.com/watch?v=W1D0XKpR5rs'],
 ['Remo con barra','Espalda','Peso libre','Barra + discos','Dorsal','Romboides, bíceps','https://www.youtube.com/watch?v=FWJR5Ve8bnQ'],
 ['Remo Pendlay','Espalda','Peso libre','Barra + discos','Espalda media','Dorsal, bíceps','https://www.youtube.com/watch?v=ZlRrIsoDpKg'],
 ['Remo mancuerna unilateral','Espalda','Peso libre','Mancuerna + banco','Dorsal','Bíceps','https://www.youtube.com/watch?v=pYcpY20QaE8'],
 ['Seal row','Espalda','Peso libre','Banco alto + barra','Espalda media','Dorsal','https://www.youtube.com/watch?v=G8l_8chR5BE'],
 ['Meadows row','Espalda','Peso libre','Barra landmine','Dorsal','Romboides','https://www.youtube.com/watch?v=AY4YjAHcWrw'],
 ['Jalón al pecho agarre ancho','Espalda','Poleas','Polea alta','Dorsal','Bíceps','https://www.youtube.com/watch?v=CAwf7n6Luuc'],
 ['Jalón neutro','Espalda','Poleas','Polea alta + agarre neutro','Dorsal','Bíceps','https://www.youtube.com/watch?v=CAwf7n6Luuc'],
 ['Jalón unilateral','Espalda','Poleas','Polea alta + maneral','Dorsal','Bíceps','https://www.youtube.com/watch?v=CAwf7n6Luuc'],
 ['Remo sentado en polea','Espalda','Poleas','Polea baja','Dorsal','Romboides, bíceps','https://www.youtube.com/watch?v=GZbfZ033f74'],
 ['Pullover en polea','Espalda','Poleas','Polea alta + cuerda/barra','Dorsal','Redondo mayor','https://www.youtube.com/watch?v=AjCCGN2tU3Q'],
 ['Remo Hammer','Espalda','Máquinas','Máquina remo','Dorsal','Romboides','https://www.youtube.com/watch?v=8MKGArS7wWQ'],
 ['High row máquina','Espalda','Máquinas','Máquina high row','Dorsal alto','Bíceps','https://www.youtube.com/watch?v=8MKGArS7wWQ'],
 ['Pulldown convergente','Espalda','Máquinas','Máquina dorsal','Dorsal','Bíceps','https://www.youtube.com/watch?v=8MKGArS7wWQ'],
 ['Press militar con barra','Hombro','Peso libre','Barra','Deltoides','Tríceps','https://www.youtube.com/watch?v=2yjwXTZQDDI'],
 ['Elevaciones laterales mancuernas','Hombro','Peso libre','Mancuernas','Deltoides lateral','Trapecio','https://www.youtube.com/watch?v=3VcKaXpzqRo'],
 ['Pájaros con mancuernas','Hombro','Peso libre','Mancuernas','Deltoides posterior','Trapecio medio','https://www.youtube.com/watch?v=ttvfGg9d76c'],
 ['Elevación lateral en polea','Hombro','Poleas','Polea baja','Deltoides lateral','Trapecio','https://www.youtube.com/watch?v=q5sNYB1Q6aM'],
 ['Face pull','Hombro','Poleas','Polea + cuerda','Deltoides posterior','Rotadores','https://www.youtube.com/watch?v=rep-qVOkqgk'],
 ['Press hombro máquina','Hombro','Máquinas','Máquina press','Deltoides','Tríceps','https://www.youtube.com/watch?v=WvLMauqrnK8'],
 ['Curl bíceps barra','Bíceps','Peso libre','Barra','Bíceps','Braquial','https://www.youtube.com/watch?v=kwG2ipFRgfo'],
 ['Curl inclinado mancuernas','Bíceps','Peso libre','Banco inclinado + mancuernas','Bíceps','Braquial','https://www.youtube.com/watch?v=soxrZlIl35U'],
 ['Curl bíceps polea','Bíceps','Poleas','Polea baja','Bíceps','Braquial','https://www.youtube.com/watch?v=NFzTWp2qpiE'],
 ['Curl predicador máquina','Bíceps','Máquinas','Máquina predicador','Bíceps','Braquial','https://www.youtube.com/watch?v=fIWP-FRFNU0'],
 ['Press francés barra Z','Tríceps','Peso libre','Barra Z + banco','Tríceps','Antebrazo','https://www.youtube.com/watch?v=d_KZxkY_0cM'],
 ['Extensión tríceps polea cuerda','Tríceps','Poleas','Polea alta + cuerda','Tríceps','Antebrazo','https://www.youtube.com/watch?v=2-LAMcpzODU'],
 ['Fondos en máquina','Tríceps','Máquinas','Máquina fondos','Tríceps','Pecho','https://www.youtube.com/watch?v=0326dy_-CzM'],
 ['Sentadilla trasera','Cuádriceps','Peso libre','Barra + rack','Cuádriceps','Glúteo','https://www.youtube.com/watch?v=ultWZbUMPL8'],
 ['Zancadas caminando','Cuádriceps','Peso libre','Mancuernas','Cuádriceps','Glúteo','https://www.youtube.com/watch?v=wrwwXE_x-pQ'],
 ['Extensión cuádriceps','Cuádriceps','Máquinas','Máquina extensora','Cuádriceps','-','https://www.youtube.com/watch?v=YyvSfVjQeL0'],
 ['Prensa inclinada','Cuádriceps','Máquinas','Prensa','Cuádriceps','Glúteo','https://www.youtube.com/watch?v=IZxyjW7MPJQ'],
 ['Peso muerto rumano','Isquios','Peso libre','Barra','Isquios','Glúteo, espalda baja','https://www.youtube.com/watch?v=JCXUYuzwNrM'],
 ['Curl femoral tumbado','Isquios','Máquinas','Máquina femoral','Isquios','Gemelo','https://www.youtube.com/watch?v=1Tq3QdYUuHs'],
 ['Pull through polea','Glúteo','Poleas','Polea baja + cuerda','Glúteo','Isquios','https://www.youtube.com/watch?v=F0g0Ck4oZ4g'],
 ['Hip thrust barra','Glúteo','Peso libre','Barra + banco','Glúteo','Isquios','https://www.youtube.com/watch?v=SEdqd1n0cvg'],
 ['Abducción máquina','Glúteo','Máquinas','Máquina abductora','Glúteo medio','Glúteo menor','https://www.youtube.com/watch?v=G_8LItOiZ0Q'],
 ['Gemelo de pie','Gemelos','Máquinas','Máquina gemelo','Gemelo','Sóleo','https://www.youtube.com/watch?v=gwLzBJYoWlI'],
 ['Gemelo sentado','Gemelos','Máquinas','Máquina gemelo sentado','Sóleo','Gemelo','https://www.youtube.com/watch?v=YMmgqO8Jo-k'],
 ['Crunch polea','Abdomen','Poleas','Polea alta + cuerda','Abdomen','Oblicuos','https://www.youtube.com/watch?v=2fbujeH3F0E'],
 ['Plancha abdominal','Abdomen','Peso libre','Suelo','Abdomen','Core','https://www.youtube.com/watch?v=pSHjTRCQxIw'],
 ['Máquina abdominal','Abdomen','Máquinas','Máquina crunch','Abdomen','Oblicuos','https://www.youtube.com/watch?v=_O1xunCfYEM']
];

const extraNames = {
 'Pecho': { 'Peso libre':['Press banca agarre cerrado','Press banca pausa','Press inclinado barra','Press declinado barra','Press suelo mancuernas','Flexiones lastradas','Flexiones pies elevados','Press hexagonal mancuernas','Pullover mancuerna','Aperturas banco inclinado'], 'Poleas':['Apertura polea media','Apertura unilateral polea','Press unilateral polea','Cruce poleas descendente','Cruce poleas ascendente','Press arrodillado polea','Aperturas polea baja','Aperturas polea alta','Press polea split stance','Squeeze press polea'], 'Máquinas':['Chest press horizontal','Chest press inclinado','Chest press declinado','Press unilateral máquina','Máquina convergente alta','Máquina convergente baja','Pec deck unilateral','Aperturas máquina inclinada','Smith press banca','Smith press inclinado']},
 'Espalda': { 'Peso libre':['Remo Yates','Remo T-Bar','Remo pecho apoyado mancuernas','Remo banco inclinado','Dominadas pronas','Dominadas neutras','Dominadas supinas','Rack pull','Remo invertido','Pullover barra'], 'Poleas':['Remo unilateral polea','Remo sentado abierto','Remo sentado cerrado','Remo alto polea','High row polea','Jalón supino','Jalón agarre V','Jalón tras nuca no recomendado','Pullover unilateral','Remo polea a pecho'], 'Máquinas':['Remo pecho apoyado','Remo iso-lateral','Máquina dorsal unilateral','Pullover máquina','Lat pulldown guiado','Remo horizontal guiado','Low row máquina','Remo articulado','Remo sentado máquina','Dorsal Hammer unilateral']},
 'Hombro': { 'Peso libre':['Press Arnold','Press mancuerna sentado','Press mancuerna de pie','Elevación frontal disco','Elevación lateral inclinado','Remo al mentón barra','Pájaros banco inclinado','Y raise mancuernas','Press landmine','Elevación lateral parcial'], 'Poleas':['Elevación frontal polea','Pájaros polea','Y raise polea','Remo alto polea','Elevación lateral unilateral','Elevación lateral detrás del cuerpo','Rotación externa polea','Press polea unilateral','Face pull alto','Face pull bajo'], 'Máquinas':['Elevación lateral máquina','Pájaros máquina','Press militar máquina','Press convergente hombro','Máquina deltoides posterior','Smith press militar','Máquina lateral unilateral','Máquina shoulder press agarre neutro','Reverse pec deck','Máquina frontal']},
 'Bíceps': { 'Peso libre':['Curl martillo','Curl spider','Curl concentración','Curl barra Z','Curl 21','Curl alterno supino','Curl Zottman','Curl banco predicador barra','Curl drag','Curl inverso barra'], 'Poleas':['Curl cuerda','Curl barra recta polea','Curl barra Z polea','Curl unilateral polea','Curl bayesian','Curl alto doble polea','Curl martillo polea','Curl predicador polea','Curl tumbado polea','Curl inverso polea'], 'Máquinas':['Curl máquina sentado','Curl máquina unilateral','Curl predicador máquina','Curl bíceps plate loaded','Curl bíceps selectorizado','Curl máquina agarre neutro','Curl Scott máquina','Curl bilateral máquina','Curl aislado máquina','Curl banco máquina']},
 'Tríceps': { 'Peso libre':['Press banca cerrado','Fondos entre bancos','Extensión mancuerna tras nuca','Extensión unilateral mancuerna','Skull crusher mancuernas','Tate press','JM press','Patada tríceps mancuerna','Press francés mancuerna','Fondos paralelas tríceps'], 'Poleas':['Extensión barra recta','Extensión barra V','Extensión unilateral polea','Extensión overhead cuerda','Extensión overhead barra','Patada tríceps polea','Pressdown agarre inverso','Extensión cruzada polea','Extensión arrodillado','Extensión cuerda unilateral'], 'Máquinas':['Press tríceps máquina','Fondos asistidos','Dip machine','Extensión tríceps máquina','Tríceps plate loaded','Máquina press cerrado','Máquina extensión sentado','Fondos máquina unilateral','Tríceps convergente','Máquina pushdown']},
 'Cuádriceps': { 'Peso libre':['Sentadilla frontal','Sentadilla goblet','Sentadilla safety bar','Sentadilla búlgara','Step up','Zancada atrás','Zancada frontal','Hack squat barra','Sissy squat','Sentadilla talones elevados'], 'Poleas':['Sentadilla polea baja','Zancada polea','Step up polea','Extensión pierna polea','Spanish squat polea','Sentadilla goblet polea','Split squat polea','Adelante-atrás polea','Terminal knee extension','Sentadilla cinturón polea'], 'Máquinas':['Hack squat','Pendulum squat','Belt squat','Prensa horizontal','Prensa unilateral','Extensión unilateral','Extensión bilateral','Sentadilla smith','Split squat smith','Máquina squat']},
 'Isquios': { 'Peso libre':['Buenos días','Peso muerto piernas rígidas','Nordic curl','Curl femoral con mancuerna','Hip hinge mancuerna','Peso muerto unilateral','RDL mancuernas','Buenos días safety bar','Glute ham raise','Slider leg curl'], 'Poleas':['Curl femoral polea','Curl femoral unilateral polea','Pull through isquios','RDL polea baja','Buenos días polea','Curl femoral de pie polea','Curl femoral tumbado polea','Hip hinge polea','Extensión cadera polea','Peso muerto polea'], 'Máquinas':['Curl femoral sentado','Curl femoral tumbado','Curl femoral de pie','Glute ham machine','Máquina peso muerto','Máquina posterior chain','Curl femoral unilateral','Curl femoral plate loaded','Máquina bisagra cadera','Máquina buenos días']},
 'Glúteo': { 'Peso libre':['Hip thrust mancuerna','Puente glúteo barra','Sentadilla sumo','Peso muerto sumo','Zancada larga','Búlgara dominante glúteo','Step up alto','Frog pumps','Kickback con mancuerna','Hip thrust unilateral'], 'Poleas':['Patada glúteo polea','Abducción polea','Pull through glúteo','Hip thrust polea','Sentadilla sumo polea','Zancada larga polea','Kickback cruzado','Extensión cadera polea','Abducción de pie','Patada glúteo lateral'], 'Máquinas':['Hip thrust máquina','Glute drive','Patada glúteo máquina','Abductora','Prensa pies altos','Hack glúteo','Máquina puente glúteo','Máquina extensión cadera','Glúteo selectorizado','Máquina abducción inclinada']},
 'Gemelos': { 'Peso libre':['Gemelo de pie mancuernas','Gemelo unilateral mancuerna','Gemelo en escalón','Gemelo barra smith','Farmer walk puntas','Gemelo donkey libre','Gemelo sentado con discos','Gemelo prensa manual','Elevación talones barra','Gemelo unilateral escalón'], 'Poleas':['Gemelo polea baja','Gemelo unilateral polea','Gemelo sentado polea','Gemelo en escalón polea','Gemelo donkey polea','Gemelo con cinturón polea','Sóleo polea','Gemelo puntas polea','Elevación talones polea','Gemelo unilateral con apoyo'], 'Máquinas':['Gemelo prensa','Gemelo donkey máquina','Gemelo hack','Gemelo smith','Gemelo horizontal','Gemelo unilateral máquina','Gemelo sentado plate loaded','Gemelo de pie selectorizado','Gemelo prensa unilateral','Sóleo máquina']},
 'Abdomen': { 'Peso libre':['Crunch suelo','Crunch inverso','Elevación piernas colgado','Dead bug','Ab wheel','Russian twist','Hollow hold','Sit up','Mountain climbers','Farmer carry'], 'Poleas':['Pallof press','Woodchopper alto-bajo','Woodchopper bajo-alto','Crunch unilateral polea','Anti-rotación polea','Elevación rodillas polea','Crunch de pie polea','Rotación tronco polea','Plancha con polea','Press pallof arrodillado'], 'Máquinas':['Crunch máquina','Rotación torso máquina','Ab coaster','Elevación piernas máquina','Máquina abdominal plate loaded','Máquina oblicuos','Crunch sentado','Abdominal guiado','Máquina core','Máquina flexión tronco']}
};

function makeExercises(){
 let arr = baseExercises.map((r,i)=>exObj(r,i)); let id=arr.length+1;
 muscles.forEach(m=>types.forEach(t=>(extraNames[m]?.[t]||[]).forEach(n=>arr.push(exObj([n,m,t,defaultMaterial(t,m),primary(m),secondary(m),''],id++)))));
 const saved = JSON.parse(localStorage.getItem('hsb_extras')||'[]');
 return [...arr,...saved];
}
function exObj(r,i){return {id:i+1,name:r[0],muscle:r[1],type:r[2],material:r[3],primary:r[4],secondary:r[5],video:r[6],favorite:false};}
function defaultMaterial(t,m){return t==='Peso libre'?'Barra/mancuernas + banco si procede':t==='Poleas'?'Polea + agarre adecuado':'Máquina específica';}
function primary(m){return m==='Espalda'?'Dorsal / espalda media':m==='Pecho'?'Pectoral':m;}
function secondary(m){return ({Pecho:'Tríceps, hombro anterior',Espalda:'Bíceps, romboides, trapecio',Hombro:'Trapecio, tríceps según ejercicio',Bíceps:'Braquial, antebrazo',Tríceps:'Antebrazo, hombro según ejercicio',Cuádriceps:'Glúteo, core',Isquios:'Glúteo, espalda baja',Glúteo:'Isquios, core',Gemelos:'Sóleo',Abdomen:'Oblicuos, core profundo'})[m]||'-';}

const foods = [
 ['Pechuga pollo','Proteínas',110,23,0,1],['Contramuslo pollo','Proteínas',170,19,0,9],['Pavo','Proteínas',105,23,0,1],['Ternera 5%','Proteínas',140,21,0,5],['Ternera 10%','Proteínas',176,20,0,10],['Solomillo cerdo','Proteínas',135,22,0,5],['Lomo embuchado','Proteínas',290,50,2,8],['Jamón serrano','Proteínas',240,31,0,12],['Cecina','Proteínas',250,39,0,9],['Atún natural','Proteínas',110,24,0,1],['Salmón','Proteínas',208,20,0,13],['Merluza','Proteínas',80,17,0,1],['Huevos','Proteínas',143,13,1,10],['Claras','Proteínas',48,11,1,0],['Skyr','Proteínas',62,11,4,0],['Queso fresco batido','Proteínas',50,8,4,0],
 ['Arroz blanco','Hidratos',360,7,78,1],['Arroz basmati','Hidratos',354,8,77,1],['Pasta','Hidratos',350,12,70,2],['Patata','Hidratos',77,2,17,0],['Boniato','Hidratos',86,2,20,0],['Pan blanco','Hidratos',265,9,49,3],['Pan integral','Hidratos',247,11,41,4],['Avena','Hidratos',370,13,60,7],['Tortitas arroz','Hidratos',387,8,82,3],['Corn Flakes','Hidratos',370,7,84,1],['Ñoquis','Hidratos',160,4,32,1],['Wrap trigo','Hidratos',310,8,52,8],
 ['Aceite oliva','Grasas',884,0,0,100],['Aguacate','Grasas',160,2,9,15],['Nueces','Grasas',654,15,14,65],['Almendras','Grasas',579,21,22,50],['Anacardos','Grasas',553,18,30,44],['Pistachos','Grasas',560,20,28,45],['Crema cacahuete','Grasas',588,25,20,50],['Queso curado','Grasas',390,26,1,32],['Chocolate 85%','Grasas',600,10,19,52],['Aceitunas','Grasas',145,1,4,15],
 ['Manzana','Frutas',52,0,14,0],['Plátano','Frutas',89,1,23,0],['Naranja','Frutas',47,1,12,0],['Fresas','Frutas',32,1,8,0],['Arándanos','Frutas',57,1,14,0],
 ['Big Mac','Restaurantes',508,26,42,25],['McPollo','Restaurantes',426,18,44,18],['Whopper','Restaurantes',657,28,49,40],['Patatas fritas medianas','Restaurantes',340,4,44,16],['Pizza margarita','Restaurantes',266,11,33,10],
 ['Yogur proteico Mercadona','Supermercados',58,10,4,0],['Queso fresco batido Hacendado','Supermercados',50,8,4,0],['Pan protein','Supermercados',260,20,18,10]
];

function logged(){return localStorage.getItem('hsb_logged')==='1'}
function app(){document.getElementById('app').innerHTML = logged()?layout():login(); bind();}
function login(){return `<div class="login"><div class="loginbox"><div class="brand"><div class="logo">HSB</div><div><h1>APP HSB</h1><p>Fuertes Sin Barriga</p></div></div><h2>Acceso clientes</h2><p class="small">Introduce el código provisional de acceso.</p><input id="pass" class="input" placeholder="Código de acceso"><br><br><button class="btn" id="loginBtn">Entrar</button><p class="small">Código demo: HSB2026</p></div></div>`}
function layout(){return `<div class="wrap"><div class="top"><div class="brand"><div class="logo">HSB</div><div><h1>APP HSB</h1><p>Biblioteca, nutrición, calculadora y formación</p></div></div><button class="pill" id="logout">Salir</button></div>${content()}<div class="nav">${navBtn('inicio','Inicio')} ${navBtn('ejercicios','Ejercicios')} ${navBtn('nutricion','Nutrición')} ${navBtn('calculadora','Calorías')} ${navBtn('formacion','Formación')} ${navBtn('admin','Admin')}</div></div>`}
function navBtn(k,t){return `<button data-tab="${k}" class="${state.tab===k?'active':''}">${t}</button>`}
function content(){return ({inicio:home,ejercicios:exercises,nutricion:nutrition,calculadora:calculator,formacion:formation,admin:admin})[state.tab]();}
function home(){return `<div class="hero"><h2>El ecosistema HSB para clientes que quieren dejar de improvisar.</h2><p>Ejercicios explicados fácil, nutrición práctica, calculadora de calorías y formación para entender RIR, fatiga, técnica y progresión.</p></div><br><div class="grid cards"><div class="card stat"><b>${makeExercises().length}</b><span>Ejercicios cargados</span></div><div class="card stat"><b>${foods.length}</b><span>Alimentos demo</span></div><div class="card stat"><b>RIR 1-2</b><span>Metodología HSB</span></div><div class="card stat"><b>V1</b><span>Lista para subir</span></div></div><br><div class="notice"><b>Nota:</b> esta V1 funciona sin servidor. El panel admin guarda nuevos ejercicios en este navegador. Para login real y usuarios reales, la siguiente fase sería Supabase + Vercel.</div>`}
function filters(){return `<div class="toolbar"><input class="input search" id="q" value="${state.q}" placeholder="Buscar ejercicio..."><select id="muscle"><option value="todos">Todos los músculos</option>${muscles.map(m=>`<option ${state.muscle===m?'selected':''}>${m}</option>`).join('')}</select><select id="type"><option value="todos">Todos los tipos</option>${types.map(t=>`<option ${state.type===t?'selected':''}>${t}</option>`).join('')}</select></div>`}
function exercises(){let data=makeExercises().filter(e=>(state.muscle==='todos'||e.muscle===state.muscle)&&(state.type==='todos'||e.type===state.type)&&(`${e.name} ${e.muscle} ${e.type}`.toLowerCase().includes(state.q.toLowerCase())));return `<div class="section"><h2>Biblioteca de ejercicios</h2><p class="small">Dividido por peso libre, poleas y máquinas. Cada ficha está preparada para vídeo directo, técnica, calzado y anatomía.</p>${filters()}<div class="list">${data.map(e=>`<button class="item" data-ex="${e.id}"><h3>${e.name}</h3><div class="meta"><span class="tag red">${e.muscle}</span><span class="tag">${e.type}</span><span class="tag">${e.material}</span></div></button>`).join('')}</div></div>${state.current?modal(state.current):''}`}
function anatomy(m){let front=m!=='Espalda'&&m!=='Isquios'; return `<div class="human"><svg viewBox="0 0 160 220"><circle class="face" cx="80" cy="24" r="18"/><rect class="bodyline" x="56" y="44" width="48" height="72" rx="18"/><rect class="bodyline" x="35" y="50" width="20" height="72" rx="10"/><rect class="bodyline" x="105" y="50" width="20" height="72" rx="10"/><rect class="bodyline" x="58" y="116" width="19" height="78" rx="9"/><rect class="bodyline" x="83" y="116" width="19" height="78" rx="9"/>${muscleSvg(m,front)}<circle cx="74" cy="22" r="2" fill="#111"/><circle cx="86" cy="22" r="2" fill="#111"/><path d="M75 31 Q80 34 86 31" stroke="#111" fill="none" stroke-width="1.5"/></svg><p class="small">Vista ${front?'frontal':'trasera'} completa. Zona principal en rojo.</p></div>`}
function muscleSvg(m,f){if(m==='Pecho')return '<ellipse class="muscle" cx="69" cy="68" rx="14" ry="17"/><ellipse class="muscle" cx="91" cy="68" rx="14" ry="17"/>'; if(m==='Espalda')return '<path class="muscle" d="M58 54 C44 72 45 100 65 111 L76 82 Z"/><path class="muscle" d="M102 54 C116 72 115 100 95 111 L84 82 Z"/>'; if(m==='Hombro')return '<circle class="muscle" cx="50" cy="56" r="12"/><circle class="muscle" cx="110" cy="56" r="12"/>'; if(m==='Bíceps')return '<rect class="muscle" x="38" y="70" width="13" height="35" rx="6"/><rect class="muscle" x="109" y="70" width="13" height="35" rx="6"/>'; if(m==='Tríceps')return '<rect class="muscle" x="34" y="68" width="13" height="39" rx="6"/><rect class="muscle" x="113" y="68" width="13" height="39" rx="6"/>'; if(m==='Cuádriceps')return '<rect class="muscle" x="59" y="120" width="16" height="50" rx="8"/><rect class="muscle" x="85" y="120" width="16" height="50" rx="8"/>'; if(m==='Isquios')return '<rect class="muscle" x="59" y="122" width="16" height="52" rx="8"/><rect class="muscle" x="85" y="122" width="16" height="52" rx="8"/>'; if(m==='Glúteo')return '<ellipse class="muscle" cx="68" cy="118" rx="13" ry="12"/><ellipse class="muscle" cx="92" cy="118" rx="13" ry="12"/>'; if(m==='Gemelos')return '<ellipse class="muscle" cx="67" cy="176" rx="9" ry="20"/><ellipse class="muscle" cx="93" cy="176" rx="9" ry="20"/>'; return '<rect class="muscle" x="68" y="70" width="24" height="43" rx="10"/>';}
function modal(id){let e=makeExercises().find(x=>x.id==id); if(!e)return '';return `<div class="modal"><div class="modalbox"><button class="close" id="close">Cerrar</button><h2>${e.name}</h2><div class="detail"><div class="anatomy">${anatomy(e.muscle)}</div><div><div class="meta"><span class="tag red">${e.primary}</span><span class="tag">${e.type}</span><span class="tag">${e.material}</span></div><div class="info-block"><b>Vídeo:</b><br>${e.video?`<a class="btn" href="${e.video}" target="_blank" rel="noopener">▶ Ver ejercicio directo</a>`:'<span class="small">Pendiente de pegar URL directa de YouTube.</span>'}</div><h3>Técnica simple</h3><p>Coloca el cuerpo estable antes de empezar. Ajusta banco, asiento o polea para que el movimiento salga cómodo y puedas controlar todo el recorrido.</p><ul><li>Pies firmes y sin bailar durante la serie.</li><li>Espalda estable. No busques hacer trampa para levantar más peso.</li><li>Controla la bajada y aprieta fuerte en la parte útil del movimiento.</li><li>Para máquinas y poleas puedes acercarte más al fallo. En peso libre, normalmente máximo RIR 1.</li></ul><h3>Calzado recomendado</h3><p>Preferible zapatilla plana: barefoot, Converse o Vans. Evita running con mucha amortiguación en ejercicios de fuerza exigentes.</p><h3>Errores frecuentes</h3><p>Usar impulso, acortar recorrido, perder la posición, mover pies o elegir una carga que no puedes dominar.</p><h3>Alternativas</h3><p>Busca otro ejercicio del mismo músculo y mismo tipo, o cambia a máquina/polea si necesitas más seguridad.</p></div></div></div></div>`}
function nutrition(){let q=state.q.toLowerCase();let cats=[...new Set(foods.map(f=>f[1]))];let data=foods.filter(f=>f[0].toLowerCase().includes(q)||f[1].toLowerCase().includes(q));return `<h2>Biblioteca nutricional</h2><p class="small">Base demo ampliable a cientos o miles de alimentos. Calorías y macros por 100 g.</p><div class="toolbar"><input class="input search" id="q" value="${state.q}" placeholder="Buscar alimento, restaurante o supermercado..."></div>${cats.map(c=>`<h3>${c}</h3><div class="list">${data.filter(f=>f[1]===c).map(f=>`<div class="item"><h3>${f[0]}</h3><div class="meta"><span class="tag red">${f[2]} kcal</span><span class="tag">P ${f[3]}g</span><span class="tag">H ${f[4]}g</span><span class="tag">G ${f[5]}g</span></div></div>`).join('')||'<p class="small">Sin resultados.</p>'}</div>`).join('')}`}
function calculator(){return `<h2>Calculadora de calorías HSB</h2><div class="card"><div class="calcgrid"><input class="input" id="age" placeholder="Edad" type="number"><input class="input" id="weight" placeholder="Peso kg" type="number"><input class="input" id="height" placeholder="Altura cm" type="number"><select id="sex" class="input"><option value="male">Hombre</option><option value="female">Mujer</option></select><input class="input" id="steps" placeholder="Pasos diarios" type="number"><input class="input" id="training" placeholder="Entrenos/semana" type="number"><select id="goal" class="input"><option value="loss">Perder grasa</option><option value="maintain">Mantener</option><option value="gain">Ganar músculo</option></select></div><br><button class="btn" id="calc">Calcular</button><div id="calcResult"></div></div><p class="small">Esto es una estimación. Lo que manda es la evolución real de tu peso, medidas y adherencia.</p>`}
function formation(){return `<h2>Formación HSB</h2><div class="grid"><div class="card lesson"><h3>Qué es el RIR</h3><p>RIR significa repeticiones en reserva. Es cuántas repeticiones buenas te quedarían al terminar una serie.</p><div class="quote">Terminas una serie y te pregunto: “¿cuántas más podrías haber hecho con buena técnica?”. Esa respuesta es tu RIR.</div></div><div class="card lesson"><h3>Metáfora clara</h3><p><b>RIR 2:</b> te quedarían dos. <b>RIR 1:</b> te quedaría una. <b>RIR 0:</b> te doy 1.000€ por sacar otra, lo intentas y no sale.</p><p><b>Fallo absoluto:</b> te apuntan con una pistola, intentas sacar otra repetición y tampoco sale. Eso no hace falta buscarlo para progresar.</p></div><div class="card lesson"><h3>Cómo lo usamos en HSB</h3><p><b>Máquinas y poleas:</b> muchas veces RIR 1-2 y algunas veces RIR 0 si procede.</p><p><b>Peso libre:</b> normalmente RIR 2 o RIR 1. RIR 0 está fuera de lugar en la mayoría de casos porque aumenta riesgo y fatiga.</p></div><div class="card lesson"><h3>Fatiga</h3><p>Señales: pierdes fuerza varias sesiones, duermes peor, entrenas con apatía, te cuesta recuperar, tienes molestias raras o cada semana te pesa más todo.</p></div></div>`}
function admin(){return `<h2>Panel admin demo</h2><p class="small">Añade ejercicios sin tocar código. Se guardan en este navegador. En la versión profesional real esto iría a Supabase.</p><div class="card adminform"><input id="aname" class="input" placeholder="Nombre ejercicio"><select id="amuscle" class="input">${muscles.map(m=>`<option>${m}</option>`).join('')}</select><select id="atype" class="input">${types.map(t=>`<option>${t}</option>`).join('')}</select><input id="amaterial" class="input" placeholder="Material"><input id="avideo" class="input" placeholder="URL directa YouTube"><button class="btn" id="addEx">Añadir ejercicio</button></div>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.current=null;state.q='';app()});let l=document.getElementById('loginBtn'); if(l)l.onclick=()=>{if(document.getElementById('pass').value===PASSWORD){localStorage.setItem('hsb_logged','1');app()}else alert('Código incorrecto')};let lo=document.getElementById('logout'); if(lo)lo.onclick=()=>{localStorage.removeItem('hsb_logged');app()};let q=document.getElementById('q'); if(q)q.oninput=e=>{state.q=e.target.value;app()};let m=document.getElementById('muscle'); if(m)m.onchange=e=>{state.muscle=e.target.value;app()};let t=document.getElementById('type'); if(t)t.onchange=e=>{state.type=e.target.value;app()};document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>{state.current=b.dataset.ex;app()});let c=document.getElementById('close'); if(c)c.onclick=()=>{state.current=null;app()};let calc=document.getElementById('calc'); if(calc)calc.onclick=calcCalories;let add=document.getElementById('addEx'); if(add)add.onclick=addExercise;}
function calcCalories(){let age=+v('age'),w=+v('weight'),h=+v('height'),steps=+v('steps'),tr=+v('training'),sex=v('sex'),goal=v('goal'); if(!age||!w||!h)return alert('Rellena edad, peso y altura');let bmr=sex==='male'?10*w+6.25*h-5*age+5:10*w+6.25*h-5*age-161;let activity=1.25+(steps/10000)*0.18+(tr*0.035);let maint=Math.round(bmr*activity);let target=goal==='loss'?maint-400:goal==='gain'?maint+250:maint;let protein=Math.round(w*2);document.getElementById('calcResult').innerHTML=`<br><div class="result">${target} kcal/día</div><p>Mantenimiento estimado: <b>${maint} kcal</b>. Proteína orientativa: <b>${protein} g/día</b>.</p>`}
function v(id){return document.getElementById(id).value}
function addExercise(){let saved=JSON.parse(localStorage.getItem('hsb_extras')||'[]');saved.push({id:10000+Date.now(),name:v('aname'),muscle:v('amuscle'),type:v('atype'),material:v('amaterial')||defaultMaterial(v('atype'),v('amuscle')),primary:primary(v('amuscle')),secondary:secondary(v('amuscle')),video:v('avideo')});localStorage.setItem('hsb_extras',JSON.stringify(saved));alert('Ejercicio añadido');state.tab='ejercicios';app()}
app();
